title:              PhD
email:              email@domain.com
description:        Explore my research, blog posts, and more.
author:             João Nuno Valente
baseurl:            ""
url:                "https://phd.joaonunovalente.com"
website_domain:     "https://joaonunovalente.com"


# Social Profiles
github_username:    joaonunovalente
linkedin_username:  joaonunovalente

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: "assets/books"
    values:
      sitemap: false

# Sass/SCSS Configuration
sass:
  style:           compressed
  quiet_deps:      true