title:              PhD
email:              email@domain.com
description:        Explore my research, blog posts, and more.
author:             João Nuno Valente
baseurl:            ""
url:                "https://phd.joaonunovalente.com"
website_domain:     "https://joaonunovalente.com"


# Social Profiles
github_username:    joaonunovalente
linkedin_username:  joaonunovalente

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
